print("Enter Your Personal Details")
name = input("Enter your name: ")
age = input("Enter your age: ")
gender = input("Enter your gender: ")
college = input("Enter your college name: ")
course = input("Enter your course: ")
print("Personal Details")
print("Name:", name)
print("Age:", age)
print("Gender:", gender)
print("College:", college)
print("Course:", course)
